export const sweaterProducts = [
  {
    title: "Hood",
    price: 35,
    description: "Our forever classic pull over hoodie.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    tags: ["Most Popular", "Seller", "Best Price"],
    genders: ["male", "female"],

    featured: false,
  },
  {
    title: "Zero Chill",
    price: 40,
    description:
      "Are you always being told to chill? You have Zero chill and need to relax with this hoodie then.",
    colors: ["red", "orange", "purple", "blue", "green", "pink", "yellow"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: [],
    featured: false,
  },
  {
    title: "Comfort Zone",
    price: 45,
    description: "Get comfortable with the coziest hoodie we sell.",
    colors: ["black", "white", "red", "orange", "purple", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Height Quality", "Most Popular", "Seller", "Limited Edition"],
    featured: true,
  },
  {
    title: "Z",
    price: 40,
    description:
      "Z stands for anything you can imagine, customize your Z hoodie.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Seller", "Most Popular", "Limited Edition"],
    featured: true,
  },
  {
    title: "Zero Zipper",
    price: 35,
    description:
      "Similar to our classic, this is a pull over hoodie and zipperless.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Best Price"],
    featured: false,
  },
  {
    title: "Zipper",
    price: 50,
    description:
      "This is Zero Zippers first cousin and total opposite. With more pockets than any other hoodie we have for sale.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tahs: ["Seller", "Limited Edition"],
    featured: true,
  },
  {
    title: "Chill",
    price: 40,
    description:
      "Chill in our finest. Made with a mixture of polymeric enhanced synthetic material, you will not find any hoodie more chill out there.",
    colors: ["black", "white", "red", "purple", "blue", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Highest Quality"],
    featured: false,
  },
  {
    title: "Zero Forever",
    price: 35,
    description:
      "Show your support and represent the brand being in love with Zero forever.",
    colors: ["black", "white"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Best Price"],
    featured: false,
  },
  {
    title: "Zero To Hero",
    price: 40,
    description:
      "Are you a special Hero to your family in someway or town or country? Send us your story and purchase this hoodie for $0.00.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Most Popular", "Seller"],
    featured: false,
  },
  {
    title: "Signature",
    price: 50,
    description:
      "This is Zero's signature hoodie. You will catch Zero himself wearing this one.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    tags: ["Most Popular", "Seller", "Limited Edition"],
    featured: true,
  },
];
