export const teeProducts = [
  {
    title: "Zero Special",
    price: 55,
    description:
      "Available only in black and white, Zero special is a limited edition tee made with 100% pure cotton.",
    colors: ["black", "white"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: true,
  },
  {
    title: "Zero Below",
    price: 30,
    description:
      "This tee is meant for the truly cold. Zero Below is not meant to be worn in the summer.",
    colors: ["black", "white"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: false,
  },
  {
    title: "Zero Fuxs",
    price: 30,
    description:
      "What do you give Zero fuxs about today? Represent your careless attitude.",
    colors: ["black", "white", "red", "orange", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: false,
  },
  {
    title: "Zero Hate",
    price: 20,
    description:
      "Maybe you do care & the only thing you give no fuxs about is hate! Represent your love of love.",
    colors: ["black", "white", "blue", "purple", "yellow", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: false,
  },
  {
    title: "Zero Tolerance",
    price: 25,
    description:
      "To tolerate is to accept and fail. Do you tolerate to tolerate?",
    colors: ["black", "white", "red", "orange", "purple", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: false,
  },
  {
    title: "Yeet",
    price: 30,
    description:
      "If you do not know what Yeeting is.. Turn back now. Whatever you need to Yeet, feel the expression by wearing the tee.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: true,
  },
  {
    title: "Zero To 100",
    price: 45,
    description:
      "When you wake up in the morning do you need coffee, or are you already ready?",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: true,
  },
  {
    title: "Zero Local",
    price: 25,
    description:
      "If you are not a resident of Las Vegas, this tee is not for sale.. Unless you find a way to get around it, show us proof and the tee is free.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: true,
  },
  {
    title: "Zero On Black",
    price: 40,
    description:
      "Support for the community and the betterment of welfare, 100% of the tee price goes to charity.",
    colors: [
      "black",
      "white",
      "red",
      "orange",
      "purple",
      "blue",
      "green",
      "pink",
      "yellow",
    ],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: true,
  },
  {
    title: "Zero Degrees",
    price: 50,
    description:
      "If you are the kind of person that feels a sweater is unnecessary in the winter, I present to you the jacket-tee",
    colors: ["black", "white", "red", "purple", "blue", "pink"],
    sizes: ["xs", "s", "md", "lrg", "xlrg", "xxlrg"],
    genders: ["male", "female"],
    featured: false,
  },
];
